module.exports = {
  Archive: require('./Archive.js'),
  AwsCredentials: require('./AwsCredentials.js'),
  Docker: require('./Docker.js'),
  DynamoDBGlobalSecondaryIndex: require('./DynamoDBGlobalSecondaryIndex.js'),
  DynamoDBStream: require('./DynamoDBStream.js'),
  DynamoDBTable: require('./DynamoDBTable.js'),
  ECR: require('./ECR.js'),
  HTTP: require('./HTTP.js'),
  NpmToken: require('./NpmToken.js'),
  OptionalValidator: require('./OptionalValidator.js'),
  Password: require('./Password.js'),
  Readable: require('./Readable.js'),
  S3Bucket: require('./S3Bucket.js'),
  Secrets: require('./Secrets.js'),
  SecretsManager: require('./SecretsManager.js'),
  StrictValidator: require('./StrictValidator.js'),
  TranscribeStream: require('./TranscribeStream.js'),
  userAgent: require('./userAgent.js'),
  WebSocket: require('./WebSocket.js'),
  WebSocketServer: require('./WebSocketServer.js'),
  WebSocketSecureServer: require('./WebSocketSecureServer.js'),
  ServerWebSocket: require('./ServerWebSocket.js'),
  XML: require('./XML.js'),
}
